/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chill_guy.glb --transform --types --out-dir ../src/models 
Files: chill_guy.glb [3.31MB] > /Users/sacha/Developer/Hackathons/ConUHacks2025/conuhacks-2025/public/chill_guy-transformed.glb [178.36KB] (95%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type ActionName = "BezierCircle|BezierCircle|BezierCircleAction.001";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    chill_guy: THREE.Mesh;
    Shoe: THREE.Mesh;
    Cube: THREE.Mesh;
    R_leg: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    ["Denim 01"]: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF("/models/chill_guy-transformed.glb") as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="BezierCircle" position={[0, -2.124, 0]} scale={3.383} />
        <mesh
          name="chill_guy"
          geometry={nodes.chill_guy.geometry}
          material={materials.PaletteMaterial001}
          position={[0, 0, -3.353]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={14.254}
        />
        <mesh
          name="Shoe"
          geometry={nodes.Shoe.geometry}
          material={nodes.Shoe.material}
          position={[-0.24, -2.696, 0.226]}
          rotation={[-Math.PI, 0.577, -Math.PI]}
          scale={[0.428, 0.063, 0.54]}
        />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.369]} />
        <mesh name="R_leg" geometry={nodes.R_leg.geometry} material={materials["Denim 01"]} position={[0.577, -0.942, -0.007]} scale={[0.507, 0.507, 0.426]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial003} position={[0.196, -2.838, 0]} scale={2.82} />
      </group>
    </group>
  );
}

useGLTF.preload("/chill_guy-transformed.glb");
