/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 krabs.glb --transform --types --out-dir ../src/models 
Files: krabs.glb [201.18KB] > C:\Users\carso\OneDrive\Documents\GitHub\conuhacks-2025\public\krabs-transformed.glb [57.39KB] (71%)
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mr-krabs-spongebob-d7e712d733ae4de69623cd408d68a289
Title: Mr Krabs (Spongebob)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['Cylinder002_13_-_Default_0']: THREE.Mesh
    ['Cylinder002_09_-_Default_0']: THREE.Mesh
    ['Cylinder002_08_-_Default_0']: THREE.Mesh
    ['Right_foot_01_-_Default_0']: THREE.Mesh
    ['Right_leg_03_-_Default_0']: THREE.Mesh
    ['Left_foot_01_-_Default_0']: THREE.Mesh
    ['Left_leg_03_-_Default_0']: THREE.Mesh
    ['Right_claw_01_-_Default_0']: THREE.Mesh
    ['Right_hand_01_-_Default_0']: THREE.Mesh
    ['Right_arm_01_-_Default_0']: THREE.Mesh
    ['Right_shoulder_02_-_Default_0']: THREE.Mesh
    ['Left_claw_01_-_Default_0']: THREE.Mesh
    ['Left_hand_01_-_Default_0']: THREE.Mesh
    ['Left_arm_01_-_Default_0']: THREE.Mesh
    ['Left_shoulder_02_-_Default_0']: THREE.Mesh
    ['Object002_13_-_Default_0']: THREE.Mesh
    ['Object002_09_-_Default_0']: THREE.Mesh
    ['Object002_08_-_Default_0']: THREE.Mesh
    ['Body_02_-_Default_0']: THREE.Mesh
    ['Body_01_-_Default_0']: THREE.Mesh
    ['Body_15_-_Default_0']: THREE.Mesh
    ['Body_19_-_Default_0']: THREE.Mesh
    ['Body_03_-_Default_0']: THREE.Mesh
    ['Body_20_-_Default_0']: THREE.Mesh
    ['Body_07_-_Default_0']: THREE.Mesh
    ['Body_21_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['13_-_Default']: THREE.MeshStandardMaterial
    ['09_-_Default']: THREE.MeshStandardMaterial
    ['08_-_Default']: THREE.MeshStandardMaterial
    ['01_-_Default']: THREE.MeshStandardMaterial
    ['03_-_Default']: THREE.MeshStandardMaterial
    ['02_-_Default']: THREE.MeshStandardMaterial
    ['15_-_Default']: THREE.MeshStandardMaterial
    ['19_-_Default']: THREE.MeshStandardMaterial
    ['20_-_Default']: THREE.MeshStandardMaterial
    ['07_-_Default']: THREE.MeshStandardMaterial
    ['21_-_Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/krabs-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  Object.values(materials).forEach((material) => {
    material.roughness = 0.6; 
    material.metalness = 0.2; 
  })

  React.useEffect(() => {
    if (actions['Take 001']) {
      actions['Take 001'].play() 
    }
  }, [actions])

  return (
    <RigidBody colliders="trimesh" lockRotations={true} scale={.009}>
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="RootNode">
            <group name="Body" position={[24.809, -47.264, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <group name="Cylinder002" position={[-14.394, 2.747, 148.533]}>
                <group name="Object_14" position={[-9.537, 0, 4.39]}>
                  <mesh name="Cylinder002_13_-_Default_0" geometry={nodes['Cylinder002_13_-_Default_0'].geometry} material={materials['13_-_Default']} />
                  <mesh name="Cylinder002_09_-_Default_0" geometry={nodes['Cylinder002_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                  <mesh name="Cylinder002_08_-_Default_0" geometry={nodes['Cylinder002_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                </group>
              </group>
              <group name="Right_leg" position={[-63.276, 0, -63.361]} rotation={[0, 0, Math.PI / 2]} scale={-0.306}>
                <group name="Right_foot" position={[0, -0.867, 107.886]} rotation={[-0.087, 0, 0]}>
                  <group name="Object_21" position={[0, 0.609, -108.244]}>
                    <mesh name="Right_foot_01_-_Default_0" geometry={nodes['Right_foot_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                  </group>
                </group>
                <mesh name="Right_leg_03_-_Default_0" geometry={nodes['Right_leg_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
              </group>
              <group name="Left_leg" position={[61.858, 0, -102.119]} rotation={[0, -0.175, Math.PI / 2]} scale={-0.306}>
                <group name="Left_foot" position={[0, 20.651, -124.949]} rotation={[0.087, 0, 0]}>
                  <group name="Object_27" position={[0, -407.302, -35.634]}>
                    <mesh name="Left_foot_01_-_Default_0" geometry={nodes['Left_foot_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                  </group>
                </group>
                <group name="Object_24" position={[0, -396.265, -161.789]}>
                  <mesh name="Left_leg_03_-_Default_0" geometry={nodes['Left_leg_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                </group>
              </group>
              <group name="Right_shoulder" position={[-104.311, 0, 79.083]} rotation={[0, -Math.PI / 3, -Math.PI / 2]} scale={0.261}>
                <group name="Right_arm" position={[0, 10.793, 82.016]} rotation={[0.175, 0, 0]} scale={3.836}>
                  <group name="Right_hand" position={[-1.384, -44.007, 109.541]} rotation={[Math.PI / 9, 0, 0]}>
                    <group name="Right_claw" rotation={[1.134, 0, -Math.PI]} scale={[0.52, 0.465, 0.465]}>
                      <group name="Object_37" position={[0, 8.733, 59.768]}>
                        <mesh name="Right_claw_01_-_Default_0" geometry={nodes['Right_claw_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                      </group>
                    </group>
                    <group name="Object_34" position={[0, 32.205, 57.652]}>
                      <mesh name="Right_hand_01_-_Default_0" geometry={nodes['Right_hand_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                    </group>
                  </group>
                  <mesh name="Right_arm_01_-_Default_0" geometry={nodes['Right_arm_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <mesh name="Right_shoulder_02_-_Default_0" geometry={nodes['Right_shoulder_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
              </group>
              <group name="Left_shoulder" position={[106.053, 1.384, 79.083]} rotation={[0, Math.PI / 3, Math.PI / 2]} scale={0.261}>
                <group name="Left_arm" position={[0, 10.793, 82.016]} rotation={[0.175, 0, 0]} scale={3.836}>
                  <group name="Left_hand" position={[-1.384, -44.007, 109.541]} rotation={[Math.PI / 9, 0, 0]}>
                    <group name="Left_claw" rotation={[1.134, 0, -Math.PI]} scale={[0.52, 0.465, 0.465]}>
                      <group name="Object_47" position={[0, 8.733, 59.768]}>
                        <mesh name="Left_claw_01_-_Default_0" geometry={nodes['Left_claw_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                      </group>
                    </group>
                    <group name="Object_44" position={[0, 32.205, 57.652]}>
                      <mesh name="Left_hand_01_-_Default_0" geometry={nodes['Left_hand_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                    </group>
                  </group>
                  <mesh name="Left_arm_01_-_Default_0" geometry={nodes['Left_arm_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <mesh name="Left_shoulder_02_-_Default_0" geometry={nodes['Left_shoulder_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
              </group>
              <group name="Object002" position={[15.394, 2.747, 149.371]}>
                <group name="Object_50" position={[-39.325, 0, 3.551]}>
                  <mesh name="Object002_13_-_Default_0" geometry={nodes['Object002_13_-_Default_0'].geometry} material={materials['13_-_Default']} />
                  <mesh name="Object002_09_-_Default_0" geometry={nodes['Object002_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                  <mesh name="Object002_08_-_Default_0" geometry={nodes['Object002_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                </group>
              </group>
              <mesh name="Body_02_-_Default_0" geometry={nodes['Body_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
              <mesh name="Body_01_-_Default_0" geometry={nodes['Body_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
              <mesh name="Body_15_-_Default_0" geometry={nodes['Body_15_-_Default_0'].geometry} material={materials['15_-_Default']} />
              <mesh name="Body_19_-_Default_0" geometry={nodes['Body_19_-_Default_0'].geometry} material={materials['19_-_Default']} />
              <mesh name="Body_03_-_Default_0" geometry={nodes['Body_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
              <mesh name="Body_20_-_Default_0" geometry={nodes['Body_20_-_Default_0'].geometry} material={materials['20_-_Default']} />
              <mesh name="Body_07_-_Default_0" geometry={nodes['Body_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
              <mesh name="Body_21_-_Default_0" geometry={nodes['Body_21_-_Default_0'].geometry} material={materials['21_-_Default']} />
            </group>
          </group>
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/krabs-transformed.glb')
