/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 playerpotato.glb --transform --types --out-dir ../src/models 
Files: playerpotato.glb [12.52MB] > /Users/sacha/Developer/Hackathons/ConUHacks2025/conuhacks-2025/public/playerpotato-transformed.glb [1.95MB] (84%)
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyborg-cowboy-potato-animated-809f9c1ff06143a2a53fc55b4c7980ef
Title: Cyborg Cowboy Potato (Animated)
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "3392058338048_TempMotion";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
    CC_Base_Hip_02: THREE.Bone;
    CC_Base_Pelvis_03: THREE.Bone;
    CC_Base_L_Thigh_04: THREE.Bone;
    CC_Base_L_Calf_05: THREE.Bone;
    CC_Base_L_Foot_06: THREE.Bone;
    CC_Base_L_ToeBaseShareBone_07: THREE.Bone;
    CC_Base_L_ToeBase_08: THREE.Bone;
    CC_Base_L_PinkyToe1_09: THREE.Bone;
    CC_Base_L_RingToe1_010: THREE.Bone;
    CC_Base_L_MidToe1_011: THREE.Bone;
    CC_Base_L_IndexToe1_012: THREE.Bone;
    CC_Base_L_BigToe1_013: THREE.Bone;
    CC_Base_L_CalfTwist01_014: THREE.Bone;
    CC_Base_L_CalfTwist02_015: THREE.Bone;
    CC_Base_L_KneeShareBone_016: THREE.Bone;
    CC_Base_L_ThighTwist01_017: THREE.Bone;
    CC_Base_L_ThighTwist02_018: THREE.Bone;
    CC_Base_R_Thigh_019: THREE.Bone;
    CC_Base_R_ThighTwist01_020: THREE.Bone;
    CC_Base_R_ThighTwist02_021: THREE.Bone;
    CC_Base_R_Calf_022: THREE.Bone;
    CC_Base_R_Foot_023: THREE.Bone;
    CC_Base_R_ToeBase_024: THREE.Bone;
    CC_Base_R_PinkyToe1_025: THREE.Bone;
    CC_Base_R_BigToe1_026: THREE.Bone;
    CC_Base_R_IndexToe1_027: THREE.Bone;
    CC_Base_R_MidToe1_028: THREE.Bone;
    CC_Base_R_RingToe1_029: THREE.Bone;
    CC_Base_R_ToeBaseShareBone_030: THREE.Bone;
    CC_Base_R_KneeShareBone_031: THREE.Bone;
    CC_Base_R_CalfTwist01_032: THREE.Bone;
    CC_Base_R_CalfTwist02_033: THREE.Bone;
    CC_Base_Waist_034: THREE.Bone;
    CC_Base_Spine01_035: THREE.Bone;
    CC_Base_Spine02_036: THREE.Bone;
    CC_Base_NeckTwist01_037: THREE.Bone;
    CC_Base_NeckTwist02_038: THREE.Bone;
    CC_Base_Head_039: THREE.Bone;
    CC_Base_FacialBone_040: THREE.Bone;
    CC_Base_JawRoot_041: THREE.Bone;
    CC_Base_Tongue01_00: THREE.Bone;
    CC_Base_Tongue02_042: THREE.Bone;
    CC_Base_Tongue03_043: THREE.Bone;
    CC_Base_Teeth02_044: THREE.Bone;
    CC_Base_R_Eye_045: THREE.Bone;
    CC_Base_L_Eye_046: THREE.Bone;
    CC_Base_UpperJaw_047: THREE.Bone;
    CC_Base_Teeth01_048: THREE.Bone;
    CC_Base_L_Clavicle_049: THREE.Bone;
    CC_Base_L_Upperarm_050: THREE.Bone;
    CC_Base_L_Forearm_051: THREE.Bone;
    CC_Base_L_ForearmTwist01_052: THREE.Bone;
    CC_Base_L_ForearmTwist02_053: THREE.Bone;
    CC_Base_L_ElbowShareBone_054: THREE.Bone;
    CC_Base_L_Hand_055: THREE.Bone;
    CC_Base_L_Index1_056: THREE.Bone;
    CC_Base_L_Index2_057: THREE.Bone;
    CC_Base_L_Index3_058: THREE.Bone;
    CC_Base_L_Thumb1_059: THREE.Bone;
    CC_Base_L_Thumb2_060: THREE.Bone;
    CC_Base_L_Thumb3_061: THREE.Bone;
    CC_Base_L_UpperarmTwist01_062: THREE.Bone;
    CC_Base_L_UpperarmTwist02_063: THREE.Bone;
    CC_Base_R_Clavicle_064: THREE.Bone;
    CC_Base_R_Upperarm_065: THREE.Bone;
    CC_Base_R_UpperarmTwist01_066: THREE.Bone;
    CC_Base_R_UpperarmTwist02_067: THREE.Bone;
    CC_Base_R_Forearm_068: THREE.Bone;
    CC_Base_R_ForearmTwist01_069: THREE.Bone;
    CC_Base_R_ForearmTwist02_070: THREE.Bone;
    CC_Base_R_ElbowShareBone_071: THREE.Bone;
    CC_Base_R_Hand_072: THREE.Bone;
    CC_Base_R_Thumb1_073: THREE.Bone;
    CC_Base_R_Thumb2_074: THREE.Bone;
    CC_Base_R_Thumb3_075: THREE.Bone;
    CC_Base_R_Index1_076: THREE.Bone;
    CC_Base_R_Index2_077: THREE.Bone;
    CC_Base_R_Index3_078: THREE.Bone;
    CC_Base_R_RibsTwist_079: THREE.Bone;
    CC_Base_R_Breast_080: THREE.Bone;
    CC_Base_L_RibsTwist_081: THREE.Bone;
    CC_Base_L_Breast_082: THREE.Bone;
  };
  materials: {
    Default: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>();
  const { scene, animations } = useGLTF("/models/playerpotato-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.Default}
          skeleton={nodes.Object_7.skeleton}
          morphTargetDictionary={nodes.Object_7.morphTargetDictionary}
          morphTargetInfluences={nodes.Object_7.morphTargetInfluences}
          rotation={[-Math.PI / 2, 0.001, -0.014]}
          scale={0.013}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/playerpotato-transformed.glb");
