/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 yoda.glb --transform --types --out-dir ../src/models 
Files: yoda.glb [3.58MB] > C:\Users\carso\OneDrive\Documents\GitHub\conuhacks-2025\public\yoda-transformed.glb [436.67KB] (88%)
Author: Boris.M (https://sketchfab.com/goodrice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sgp24-yoda-master-03424fd66c6c4516a24194e4065b6b2b
Title: [SGP24] Yoda Master
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RigidBody } from '@react-three/rapier'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    polySurface1_lambert1_0: THREE.Mesh
    polySurface2_lambert1_0: THREE.Mesh
    callouxGroup6879_lambert1_0: THREE.Mesh
    ZBrush_defualt_group_defaultMat_0: THREE.Mesh
    Group1_defaultMat_0: THREE.Mesh
    Group2_defaultMat_0: THREE.Mesh
    Group3_defaultMat_0: THREE.Mesh
    Group4_defaultMat_0: THREE.Mesh
    Group5_defaultMat_0: THREE.Mesh
    Group6_defaultMat_0: THREE.Mesh
    Group7_defaultMat_0: THREE.Mesh
    Group8_defaultMat_0: THREE.Mesh
    Group9_defaultMat_0: THREE.Mesh
    Group10_defaultMat_0: THREE.Mesh
    Group11_defaultMat_0: THREE.Mesh
    Group12_defaultMat_0: THREE.Mesh
    Group13_defaultMat_0: THREE.Mesh
    Group14_defaultMat_0: THREE.Mesh
    Group15_defaultMat_0: THREE.Mesh
    Group16_defaultMat_0: THREE.Mesh
    Group27_defaultMat_0: THREE.Mesh
    Group30_defaultMat_0: THREE.Mesh
  }
  materials: {
    lambert1: THREE.MeshStandardMaterial
    defaultMat: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/yoda-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  Object.values(materials).forEach((material) => {
    material.roughness = 0.9; 
    material.metalness = 0.5; 
  })

  React.useEffect(() => {
    if (actions['Take 001']) {
      actions['Take 001'].play() 
    }
  }, [actions])

  return (
    <RigidBody colliders="trimesh" lockRotations={true}>
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Object_2">
            <group name="RootNode">
              <group name="callouxGroup28251">
                <group name="polySurface1" position={[0, 0.23, 0]}>
                  <mesh name="polySurface1_lambert1_0" geometry={nodes.polySurface1_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="polySurface2">
                  <mesh name="polySurface2_lambert1_0" geometry={nodes.polySurface2_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="transform1" />
              </group>
              <group name="callouxGroup6879">
                <mesh name="callouxGroup6879_lambert1_0" geometry={nodes.callouxGroup6879_lambert1_0.geometry} material={materials.lambert1} />
              </group>
              <group name="ZBrush_defualt_group">
                <mesh name="ZBrush_defualt_group_defaultMat_0" geometry={nodes.ZBrush_defualt_group_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group1">
                <mesh name="Group1_defaultMat_0" geometry={nodes.Group1_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group2">
                <mesh name="Group2_defaultMat_0" geometry={nodes.Group2_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group3">
                <mesh name="Group3_defaultMat_0" geometry={nodes.Group3_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group4">
                <mesh name="Group4_defaultMat_0" geometry={nodes.Group4_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group5">
                <mesh name="Group5_defaultMat_0" geometry={nodes.Group5_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group6">
                <mesh name="Group6_defaultMat_0" geometry={nodes.Group6_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group7">
                <mesh name="Group7_defaultMat_0" geometry={nodes.Group7_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group8">
                <mesh name="Group8_defaultMat_0" geometry={nodes.Group8_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group9">
                <mesh name="Group9_defaultMat_0" geometry={nodes.Group9_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group10">
                <mesh name="Group10_defaultMat_0" geometry={nodes.Group10_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group11">
                <mesh name="Group11_defaultMat_0" geometry={nodes.Group11_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group12">
                <mesh name="Group12_defaultMat_0" geometry={nodes.Group12_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group13">
                <mesh name="Group13_defaultMat_0" geometry={nodes.Group13_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group14">
                <mesh name="Group14_defaultMat_0" geometry={nodes.Group14_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group15">
                <mesh name="Group15_defaultMat_0" geometry={nodes.Group15_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group16">
                <mesh name="Group16_defaultMat_0" geometry={nodes.Group16_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group27">
                <mesh name="Group27_defaultMat_0" geometry={nodes.Group27_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
              <group name="Group30">
                <mesh name="Group30_defaultMat_0" geometry={nodes.Group30_defaultMat_0.geometry} material={materials.defaultMat} />
              </group>
            </group>
          </group>
        </group>
      </group>  
    </RigidBody>
  )
}

useGLTF.preload('/yoda-transformed.glb')
